name: hydrow
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  flutter_local_notifications: ^17.1.2
  built_collection: 5.1.1
  built_value: ^8.9.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.1
  cloud_firestore_platform_interface: ^6.2.7
  cloud_firestore_web: ^4.0.1
  csv: ^6.0.0
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_auth_platform_interface: ^7.4.0
  firebase_auth_web: ^5.12.2
  firebase_core: ^3.1.0
  firebase_core_platform_interface: ^5.1.0
  firebase_core_web: ^2.17.2
  firebase_crashlytics: ^4.0.1
  firebase_crashlytics_platform_interface: ^3.6.37
  flutter_animate: ^4.5.0
  flutter_barcode_scanner:
    git:
      url: https://github.com/FlutterFlow/flutter_barcode_scanner
  flutter_cache_manager: ^3.3.1
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^14.1.4
  google_fonts: ^4.0.4
  google_sign_in: ^6.2.1
  google_sign_in_ios: ^5.7.6
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4
  http: ^0.13.5
  intl: 0.17.0
  json_path: ^0.7.2
  json_serializable: ^6.8.0
  liquid_progress_indicator: ^0.4.0
  page_transition: ^2.1.0
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0
  sqflite: ^2.3.3+1
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  webviewx_plus:
    git:
      url: https://github.com/FlutterFlow/webviewx_plus.git
  workmanager: ^0.5.1
  wave: ^0.2.2
  syncfusion_flutter_charts: ^26.1.35
  cupertino_icons: ^1.0.0
  flutter_svg: ^2.0.5
  syncfusion_flutter_gauges: ^26.1.35

  # background_fetch: '^1.1.3'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dependency_overrides:
  webview_flutter_android: 2.10.3
  webview_flutter_platform_interface: 1.9.5
  webview_flutter_wkwebview: 2.9.5
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Spartan
      fonts:
        - asset: assets/fonts/Spartan-Black.ttf
        - asset: assets/fonts/Spartan-Bold.ttf
        - asset: assets/fonts/Spartan-ExtraBold.ttf
        - asset: assets/fonts/Spartan-ExtraLight.ttf
        - asset: assets/fonts/Spartan-Light.ttf
        - asset: assets/fonts/Spartan-Medium.ttf
        - asset: assets/fonts/Spartan-Regular.ttf
        - asset: assets/fonts/Spartan-SemiBold.ttf
        - asset: assets/fonts/Spartan-Thin.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
